import { test, expect } from "@playwright/test";

test("loads issue route, creates cycle, assigns issue, adds comment and attachment", async ({ page }) => {
  await page.goto("/acme/eng/issues");
  await expect(page.getByText("Project Management UI")).toBeVisible();
  await expect(page.getByTestId("org-name")).toHaveText(/Org: Acme/);
  await expect(page.getByTestId("issues-count")).toBeVisible();
  await expect(page.getByTestId("cycles-count")).toBeVisible();
  const createCycleButton = page.getByRole("button", { name: "Create Cycle" });
  const createIssueButton = page.getByRole("button", { name: "Create Issue" });
  await expect(createCycleButton).toBeEnabled({ timeout: 20000 });
  await expect(createIssueButton).toBeEnabled({ timeout: 20000 });
  await createCycleButton.click();
  await createIssueButton.click();
  await page.getByRole("button", { name: "Assign First Issue To First Cycle" }).click();
  await page.getByRole("button", { name: "Complete First Cycle" }).click();
  await expect(page.getByTestId("cycle-status")).toHaveText(/completed/i);
  await expect(page.getByTestId("workflow-state-name")).toHaveText(/Backlog/i);
  await page.getByRole("button", { name: "Move First Issue To Next Workflow State" }).click();
  await expect(page.getByTestId("workflow-state-name")).toHaveText(/Todo/i);
  await page.getByRole("button", { name: "Add Comment To First Issue" }).click();
  await page.getByRole("button", { name: "Add Attachment To First Issue" }).click();
  await page.getByRole("button", { name: "Create API Key" }).click();
  await page.getByRole("button", { name: "Upsert Notification Preference" }).click();
  await expect(page.getByTestId("unread-notifications-count")).toBeVisible();
  await page.getByRole("button", { name: "Mark All Notifications Read" }).click();
  await expect(page.getByTestId("unread-notifications-count")).toHaveText("Unread: 0");
  await expect(page.locator("li").first()).toBeVisible();
  await expect(page.getByText("First Issue Comments")).toBeVisible();
  await page.getByRole("link", { name: "Projects" }).click();
  await expect(page.getByRole("heading", { name: "Projects" })).toBeVisible();
  await expect(page.getByTestId("projects-count")).toBeVisible();
  await page.getByRole("button", { name: "Create Project" }).click();
  await expect(page.locator("li").first()).toBeVisible();
});
